/**
 * OTUS Highload Architect
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ru.paf.highload;

import java.math.BigDecimal;
import ru.paf.highload.DialogMessage;
import ru.paf.highload.DialogUserIdSendPostRequest;
import ru.paf.highload.LoginPost200Response;
import ru.paf.highload.LoginPost500Response;
import ru.paf.highload.LoginPostRequest;
import ru.paf.highload.Post;
import ru.paf.highload.PostCreatePostRequest;
import ru.paf.highload.PostUpdatePutRequest;
import ru.paf.highload.User;
import ru.paf.highload.UserRegisterPost200Response;
import ru.paf.highload.UserRegisterPostRequest;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.ws.rs.*;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.MediaType;
import org.apache.cxf.jaxrs.ext.multipart.*;


import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

/**
 * OTUS Highload Architect
 *
 * <p>No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

@RegisterProvider(ApiExceptionMapper.class)
@Path("")
public interface DefaultApi  {

    @GET
    @Path("/dialog/{user_id}/list")
    @Produces({ "application/json" })
    List<DialogMessage> dialogUserIdListGet(@PathParam("user_id") String userId) throws ApiException, ProcessingException;

    @POST
    @Path("/dialog/{user_id}/send")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    void dialogUserIdSendPost(@PathParam("user_id") String userId, DialogUserIdSendPostRequest dialogUserIdSendPostRequest) throws ApiException, ProcessingException;

    @PUT
    @Path("/friend/delete/{user_id}")
    @Produces({ "application/json" })
    void friendDeleteUserIdPut(@PathParam("user_id") String userId) throws ApiException, ProcessingException;

    @PUT
    @Path("/friend/set/{user_id}")
    @Produces({ "application/json" })
    void friendSetUserIdPut(@PathParam("user_id") String userId) throws ApiException, ProcessingException;

    @POST
    @Path("/login")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    LoginPost200Response loginPost(LoginPostRequest loginPostRequest) throws ApiException, ProcessingException;

    @POST
    @Path("/post/create")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    String postCreatePost(PostCreatePostRequest postCreatePostRequest) throws ApiException, ProcessingException;

    @PUT
    @Path("/post/delete/{id}")
    @Produces({ "application/json" })
    void postDeleteIdPut(@PathParam("id") String id) throws ApiException, ProcessingException;

    @GET
    @Path("/post/feed")
    @Produces({ "application/json" })
    List<Post> postFeedGet(@QueryParam("offset") @DefaultValue("0") BigDecimal offset, @QueryParam("limit") @DefaultValue("10") BigDecimal limit) throws ApiException, ProcessingException;

    @GET
    @Path("/post/get/{id}")
    @Produces({ "application/json" })
    Post postGetIdGet(@PathParam("id") String id) throws ApiException, ProcessingException;

    @PUT
    @Path("/post/update")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    void postUpdatePut(PostUpdatePutRequest postUpdatePutRequest) throws ApiException, ProcessingException;

    @GET
    @Path("/user/get/{id}")
    @Produces({ "application/json" })
    User userGetIdGet(@PathParam("id") String id) throws ApiException, ProcessingException;

    @POST
    @Path("/user/register")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    UserRegisterPost200Response userRegisterPost(UserRegisterPostRequest userRegisterPostRequest) throws ApiException, ProcessingException;

    @GET
    @Path("/user/search")
    @Produces({ "application/json" })
    List<User> userSearchGet(@QueryParam("first_name") String firstName, @QueryParam("last_name") String lastName) throws ApiException, ProcessingException;
}
