/**
 * OTUS Highload Architect
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ru.paf.highload;

import java.util.Objects;
import java.util.Arrays;
import java.lang.reflect.Type;
import javax.json.bind.annotation.JsonbTypeDeserializer;
import javax.json.bind.annotation.JsonbTypeSerializer;
import javax.json.bind.serializer.DeserializationContext;
import javax.json.bind.serializer.JsonbDeserializer;
import javax.json.bind.serializer.JsonbSerializer;
import javax.json.bind.serializer.SerializationContext;
import javax.json.stream.JsonGenerator;
import javax.json.stream.JsonParser;
import javax.json.bind.annotation.JsonbProperty;


public class DialogMessage  {
  
 /**
  * Идентификатор пользователя
  */
  @JsonbProperty("from")
  private String from;

 /**
  * Идентификатор пользователя
  */
  @JsonbProperty("to")
  private String to;

 /**
  * Текст сообщения
  */
  @JsonbProperty("text")
  private String text;

  /**
   * Идентификатор пользователя
   * @return from
   **/
  public String getFrom() {
    return from;
  }

  /**
   * Set from
   */
  public void setFrom(String from) {
    this.from = from;
  }

  public DialogMessage from(String from) {
    this.from = from;
    return this;
  }

  /**
   * Идентификатор пользователя
   * @return to
   **/
  public String getTo() {
    return to;
  }

  /**
   * Set to
   */
  public void setTo(String to) {
    this.to = to;
  }

  public DialogMessage to(String to) {
    this.to = to;
    return this;
  }

  /**
   * Текст сообщения
   * @return text
   **/
  public String getText() {
    return text;
  }

  /**
   * Set text
   */
  public void setText(String text) {
    this.text = text;
  }

  public DialogMessage text(String text) {
    this.text = text;
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DialogMessage dialogMessage = (DialogMessage) o;
    return Objects.equals(this.from, dialogMessage.from) &&
        Objects.equals(this.to, dialogMessage.to) &&
        Objects.equals(this.text, dialogMessage.text);
  }

  @Override
  public int hashCode() {
    return Objects.hash(from, to, text);
  }

  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DialogMessage {\n");
    
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

