/**
 * OTUS Highload Architect
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ru.paf.highload;

import java.util.Objects;
import java.util.Arrays;
import java.util.Date;
import java.lang.reflect.Type;
import javax.json.bind.annotation.JsonbTypeDeserializer;
import javax.json.bind.annotation.JsonbTypeSerializer;
import javax.json.bind.serializer.DeserializationContext;
import javax.json.bind.serializer.JsonbDeserializer;
import javax.json.bind.serializer.JsonbSerializer;
import javax.json.bind.serializer.SerializationContext;
import javax.json.stream.JsonGenerator;
import javax.json.stream.JsonParser;
import javax.json.bind.annotation.JsonbProperty;


public class User  {
  
 /**
  * Идентификатор пользователя
  */
  @JsonbProperty("id")
  private String id;

 /**
  * Имя
  */
  @JsonbProperty("first_name")
  private String firstName;

 /**
  * Фамилия
  */
  @JsonbProperty("second_name")
  private String secondName;

 /**
  * Дата рождения
  */
  @JsonbProperty("birthdate")
  private Date birthdate;

 /**
  * Интересы
  */
  @JsonbProperty("biography")
  private String biography;

 /**
  * Город
  */
  @JsonbProperty("city")
  private String city;

  /**
   * Идентификатор пользователя
   * @return id
   **/
  public String getId() {
    return id;
  }

  /**
   * Set id
   */
  public void setId(String id) {
    this.id = id;
  }

  public User id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Имя
   * @return firstName
   **/
  public String getFirstName() {
    return firstName;
  }

  /**
   * Set firstName
   */
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public User firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

  /**
   * Фамилия
   * @return secondName
   **/
  public String getSecondName() {
    return secondName;
  }

  /**
   * Set secondName
   */
  public void setSecondName(String secondName) {
    this.secondName = secondName;
  }

  public User secondName(String secondName) {
    this.secondName = secondName;
    return this;
  }

  /**
   * Дата рождения
   * @return birthdate
   **/
  public Date getBirthdate() {
    return birthdate;
  }

  /**
   * Set birthdate
   */
  public void setBirthdate(Date birthdate) {
    this.birthdate = birthdate;
  }

  public User birthdate(Date birthdate) {
    this.birthdate = birthdate;
    return this;
  }

  /**
   * Интересы
   * @return biography
   **/
  public String getBiography() {
    return biography;
  }

  /**
   * Set biography
   */
  public void setBiography(String biography) {
    this.biography = biography;
  }

  public User biography(String biography) {
    this.biography = biography;
    return this;
  }

  /**
   * Город
   * @return city
   **/
  public String getCity() {
    return city;
  }

  /**
   * Set city
   */
  public void setCity(String city) {
    this.city = city;
  }

  public User city(String city) {
    this.city = city;
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    User user = (User) o;
    return Objects.equals(this.id, user.id) &&
        Objects.equals(this.firstName, user.firstName) &&
        Objects.equals(this.secondName, user.secondName) &&
        Objects.equals(this.birthdate, user.birthdate) &&
        Objects.equals(this.biography, user.biography) &&
        Objects.equals(this.city, user.city);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, firstName, secondName, birthdate, biography, city);
  }

  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class User {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    secondName: ").append(toIndentedString(secondName)).append("\n");
    sb.append("    birthdate: ").append(toIndentedString(birthdate)).append("\n");
    sb.append("    biography: ").append(toIndentedString(biography)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

