server:
  port: 8080
  error:
    include-message: always
spring:
  jackson:
    date-format: ru.paf.highload.invoker.RFC3339DateFormat
  serialization:
    WRITE_DATES_AS_TIMESTAMPS: false

params:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/paf_homework
    username: paf
    password: secret
    maximumPoolSize: 5
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
