/**
 * OTUS Highload Architect
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.paf.highload;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LoginPost200Response
 */
class LoginPost200ResponseTest {
    private final LoginPost200Response model = new LoginPost200Response();

    /**
     * Model tests for LoginPost200Response
     */
    @Test
    void testLoginPost200Response() {
        // TODO: test LoginPost200Response
    }

    /**
     * Test the property 'token'
     */
    @Test
    void tokenTest() {
        // TODO: test token
    }

}
