/**
 * OTUS Highload Architect
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.paf.highload;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LoginPost500Response
 */
class LoginPost500ResponseTest {
    private final LoginPost500Response model = new LoginPost500Response();

    /**
     * Model tests for LoginPost500Response
     */
    @Test
    void testLoginPost500Response() {
        // TODO: test LoginPost500Response
    }

    /**
     * Test the property 'message'
     */
    @Test
    void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'requestId'
     */
    @Test
    void requestIdTest() {
        // TODO: test requestId
    }

    /**
     * Test the property 'code'
     */
    @Test
    void codeTest() {
        // TODO: test code
    }

}
