/**
 * OTUS Highload Architect
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.paf.highload;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostCreatePostRequest
 */
class PostCreatePostRequestTest {
    private final PostCreatePostRequest model = new PostCreatePostRequest();

    /**
     * Model tests for PostCreatePostRequest
     */
    @Test
    void testPostCreatePostRequest() {
        // TODO: test PostCreatePostRequest
    }

    /**
     * Test the property 'text'
     */
    @Test
    void textTest() {
        // TODO: test text
    }

}
