/**
 * OTUS Highload Architect
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.paf.highload;

import java.util.Date;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UserRegisterPostRequest
 */
class UserRegisterPostRequestTest {
    private final UserRegisterPostRequest model = new UserRegisterPostRequest();

    /**
     * Model tests for UserRegisterPostRequest
     */
    @Test
    void testUserRegisterPostRequest() {
        // TODO: test UserRegisterPostRequest
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'secondName'
     */
    @Test
    void secondNameTest() {
        // TODO: test secondName
    }

    /**
     * Test the property 'birthdate'
     */
    @Test
    void birthdateTest() {
        // TODO: test birthdate
    }

    /**
     * Test the property 'biography'
     */
    @Test
    void biographyTest() {
        // TODO: test biography
    }

    /**
     * Test the property 'city'
     */
    @Test
    void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'password'
     */
    @Test
    void passwordTest() {
        // TODO: test password
    }

}
