/**
 * OTUS Highload Architect
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.paf.highload;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UserRegisterPost200Response
 */
class UserRegisterPost200ResponseTest {
    private final UserRegisterPost200Response model = new UserRegisterPost200Response();

    /**
     * Model tests for UserRegisterPost200Response
     */
    @Test
    void testUserRegisterPost200Response() {
        // TODO: test UserRegisterPost200Response
    }

    /**
     * Test the property 'userId'
     */
    @Test
    void userIdTest() {
        // TODO: test userId
    }

}
